region: us-west-1

function_name: UpdateMenu
handler: service.handler
role: lambda_basic_execution
description: Lambda function to update menu

aws_access_key_id:        # AWS Access Key
aws_secret_access_key:    # AWS Secret Key
